### ISSUE TITLE
Need time stamps in logs

### ISSUE THREAD

**Issue by PDegenPortnoy** [santhanakarthikeyan/multi_daemons#9]
We need the date and time of the reported events added to the log. It would be also helpful if the logs showed when the process started. This would be very helpful in identifying when a process crashed, which is critical in diagnosing issues outside of the application environment; DNS, network, SSL connection limits, etc.

**Comment by santhanakarthikeyan** [comment]
@PDegenPortnoy thanks for raising this issue. It has been addressed in this PR https://github.com/santhanakarthikeyan/multi_daemons/pull/10.
